### PR TITLE
en.yaml add description for list_set_deferrable_startup_penalty

### PR DESCRIPTION
**Pull request by GeoDerp**
sorry @werdnum,  I may be quite wrong with this, feel free to adjust.

### CODE REVIEW

**Comment by davidusb-geek** [comment]
util.py also needs to be modified accordingly to support this right? I oversaw this.

**Comment by GeoDerp** [comment]
> util.py also needs to be modified accordingly to support this right? I oversaw this.

Ah, yeah I think your right. I might make a PR today or tomorow fixing this. *(Feel free to to this before me)*

**Comment by werdnum** [comment]
> util.py also needs to be modified accordingly to support this right? I oversaw this.

Ah, looking at this it seems to be for the addon mode. That explains why I was so confused when you commented this on the original PR - I run my instance in standalone mode because I don't use HAOS.

**Review by werdnum — COMMENTED** [review]
Looks good to me, but I'm not an owner of this project so I won't approve just in case.

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
