### PR TITLE
Centralized docker file for all use cases

### PR DESCRIPTION
**Pull request by GeoDerp**
Related to https://github.com/davidusb-geek/emhass/pull/200

### CODE REVIEW

**Comment by GeoDerp** [comment]
This is not tested yet. Still need to work out how to best test this thoroughly.
If you test this yourself feel free to re-add the `finish` & `run` files. 
Sorry, I wasn't shore if they would be needed or not. *(run shouldn't be)*

**Comment by GeoDerp** [comment]
@davidusb-geek , Do we need to publish the Docker images to DockerHub for HA addons to still work?
Isn't the Add-on repository the github repository  anyways?
I commented out the `image: "davidusb/image-{arch}-emhass"` Line so the addon builds using its local  Dockerfile. 

I set `https://github.com/GeoDerp/emhass-add-on.git` as a repository and it run fine using the Local Dockerfile (besideds the fact the emhass pip needs to be updated to match the changes)

**Comment by GeoDerp** [comment]
I created a [Test.me](https://github.com/davidusb-geek/emhass-add-on/blob/76a6858e9c825ff9a4622e7e8078d5c6f6952599/emhass/Test.md)

**Comment by GeoDerp** [comment]
More then happy to uncomment the image line (just let me know).
Would be good to test the github workspaces to see if they require the build argument passed, or they copy the build arguments from build.yaml

**Comment by GeoDerp** [comment]
Just a note if you test this using the regular `addon` mode it will fail, as emhass pip its trying to find the config in `/share` directory. Testing using addon-git should work using repo from pr 200: https://github.com/GeoDerp/emhass/tree/centralized-Docker
And pip should work when built with PR 200

**Comment by GeoDerp** [comment]
> Ok I will test and see if I got all this right.
> Just one quick question, I thought that the add-on image was always pulled from Dockerhub and then loaded.
> But you are saying that it is always build locally by the user HA instance?

Good question. It depends if you have the `image: "davidusb/image-{arch}-emhass"` commented out or not in he config.yaml. That line will pull from docker hub. otherwise it will pull from git and build locally.

I have commented it out for local testing but we can add it back in.

**Comment by davidusb-geek** [comment]
Ok yes that's actually what I do when locally testing. Just comment that line and put the add-on files on the add-on folder in my HA instance, then a local add-on shows for testing. I think that we can leave the image for downloading from docker-hub, it can be useful for users with some limited resources (some Rpi's).

**Comment by GeoDerp** [comment]
> Ok yes that's actually what I do when locally testing. Just comment that line and put the add-on files on the add-on folder in my HA instance, then a local add-on shows for testing. I think that we can leave the image for downloading from docker-hub, it can be useful for users with some limited resources (some Rpi's). 

Sounds good. I'll uncomment the line and also tweak the test markdown now 👍

**Comment by GeoDerp** [comment]
If the publish worflows don't work maybe adding the line  `--generic latest`. I think this may help building based on build.yaml, but im not sure.

**Comment by GeoDerp** [comment]
example:
```yaml
  publish_armv7:
    name: Publish-armv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --armv7 \
            --target emhass \
            --docker-hub davidusb \
             --generic latest
```

**Comment by GeoDerp** [comment]
Im seeing now if we could integrate https://github.com/home-assistant/builder/blob/master/.github/workflows/test.yml into this repo to test

**Comment by GeoDerp** [comment]
https://github.com/GeoDerp/emhass-add-on/blob/live-test/.github/workflows/test.yaml

**Comment by GeoDerp** [comment]
https://github.com/GeoDerp/emhass-add-on/actions/runs/7989275935/job/21815534964

Looks like armhf failed with `#9 246.9       ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'`

**Comment by GeoDerp** [comment]
The test.yaml by the way iterates the architectures and is triggered manually or on pull request .

**Comment by davidusb-geek** [comment]
That is very nice. The armhf builds are failing since some months ago. I've tried several times to solve it without success

**Comment by GeoDerp** [comment]
@davidusb-geek 

Got it working with this 

Requirements:
```
pvlib>=0.10.2
protobuf>=3.0.0
pytz>=2021.1
requests>=2.25.1
beautifulsoup4>=4.9.3
h5py==3.10.0
pulp>=2.4
pyyaml>=5.4.1
tables<=3.9.1
skforecast==0.11.0
flask>=2.0.3
waitress>=2.1.1
plotly>=5.6.0
emhass==0.7.7
#git+https://github.com/davidusb-geek/emhass
```

Docker 
```docker
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libffi-dev \
    python3 \
    python3-pip \
    python3-dev \
    python3-numpy \
    python3-wheel \
    python3-setuptools \
    python3-setuptools-whl \
    python3-scipy \
    python3-pandas \
    git \
    build-essential \
    gcc \
    coinor-cbc \
    coinor-libcbc-dev \
    libglpk-dev \
    glpk-utils \
    libhdf5-dev \
    libhdf5-serial-dev \
    netcdf-bin \
    libnetcdf-dev \
    pkg-config \
    gfortran \
    libatlas-base-dev \
    && ln -s /usr/include/hdf5/serial /usr/include/hdf5/include \
    && export HDF5_DIR=/usr/include/hdf5 \
    && pip3 install --extra-index-url=https://www.piwheels.org/simple --no-cache-dir --break-system-packages -r requirements.txt \
    && apt-get purge -y --auto-remove \
    gcc \
    build-essential \
    libhdf5-dev \
    libhdf5-serial-dev \
    pkg-config \
    gfortran \
    && rm -rf /var/lib/apt/lists/*

```

**Comment by GeoDerp** [comment]
@davidusb-geek , Tomorrow (Friday) I'll modify the build arguments for git and then ill be pritty happy for both related PR's.
*I may also make the armhf test seperate*

**Comment by davidusb-geek** [comment]
Hi @GeoDerp, so were you able to solve the build issues for armhf archs?
I see that they are not part of the automated builds now.

**Comment by GeoDerp** [comment]
Yeah I have just set armhf to its own step so we can see the other three work. currently the workflow is broken tho. Fixing it now. And unfortunately, I haven't worked out a fix for armhf (besides bumping to python 3.11 which brakes its own issues )

**Comment by GeoDerp** [comment]
Relativity happy with it (its not perfect). Found a error when using the latest EMHASS pip with the new Docker. Will work out if that a reliant issue (as new git EMHASS works). Will also proof read my work and then done.

The error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/emhass/web_server.py", line 207, in <module>
    config_hass = response.json()
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 4 (char 3
```

**Comment by GeoDerp** [comment]
Also another note. The main issue with armhf is with python wheel. If this got fixes it would fix everything related. Alternatively updating  pandas support to the latest version would also fix the issue by setting 

```bash
    python3-numpy \
    python3-wheel \
    python3-setuptools \
    python3-setuptools-whl \
    python3-scipy \
    python3-pandas \
```    
in apt-get instead of python requirements.txt

**Comment by davidusb-geek** [comment]
Thanks for all this work John. You tell me when it's ready to merge. It seems that some tests are falling

**Comment by GeoDerp** [comment]
Hopefully I'll be able to finish it tonight.

**Comment by GeoDerp** [comment]
@davidusb-geek , Should be ready to go. Will just wait for build test confirmation.

**Comment by GeoDerp** [comment]
Just a note, the armv7 takes around a 1hr 30min to build test. My guess is that the armv7 servers are just less powerful.

**Comment by davidusb-geek** [comment]
Everything seems good. Yes that's normal for armv7, it has been like that for add-on releases. It even worst before I found the trick of passing the pywheels url. Before that it took like 10 hours!
Armhf is still failing but that won't block a new release.
It seems like a problem installing Pandas along with Python 3.11 on that arch.

**Comment by GeoDerp** [comment]
Both PR's should be ready to be tested and pulled.
No stress if you choose not to use it. 👍

Let me know if anything comes up. 😁

**Review by davidusb-geek — APPROVED** [review]

**Pull request merged**
